version: '3.8'

services:
  backend:
    build: ./server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    
  frontend:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend